### ISSUE TITLE
prefix mkfs.xtreemfs and mount.xtreemfs options

### ISSUE THREAD

**Issue by cjeanneret** [wavesoftware/puppet-xtreemfs#5] opened 2014-12-01 17:53 UTC
Hello!

Great improvements, really cool! Just a small thought: it would be pretty cool if the two types used for mkfs and mount prefixes the options with "--".

This would allow a nice and clean call, like:

``` Puppet
  ::xtreemfs::volume {'volume':
    ensure      => present,
    dir_service => "pbrpcs://${directory}",
    options     => {
      'admin_password'    => hiera('xtreemfs::admin_password'),
      'pkcs12-file-path'  => '/etc/ssl/certs/xtreemfs-client.p12',
      'pkcs12-passphrase' => hiera('xtreemfs::service_cred::pwd'),
    }
  }
```

Using this form returns an error right now, showing the lack of "--" prefixes for option names.

Thanks for you work, this module is really useful ;).

**Comment by cjeanneret** [comment] 2014-12-01 18:00
hmm, in fact, it seems the type wants the options without "--" prefix, but doesn't add it when it calls the mkfs.extreemfs binary…

**Comment by cardil** [comment] 2014-12-01 21:10
Did you try to use:

``` puppet
::xtreemfs::volume {'volume':
  ensure      => present,
  dir_service => "pbrpcs://${directory}",
  options     => {
    '--admin_password'    => hiera('xtreemfs::admin_password'),
    '--pkcs12-file-path'  => '/etc/ssl/certs/xtreemfs-client.p12',
    '--pkcs12-passphrase' => hiera('xtreemfs::service_cred::pwd'),
  }
}
```

These options should be passed directly to lsfs mkfs and rmfs commands. Does this fail for you? 

If so could you provide more info on your setup: OS, Puppet version Ruby version, and logs from puppet (please execute with `--debug --trace`)

About your point that this form will be better (without `--` signs): I thought about it. But as you see I've decided, for now, I will accept full form. Mainly because of short form options like `-f`. Sure i can add `-` sign to single char options and two `--` for longer options but this may not be obvious for new users.

**Comment by cjeanneret** [comment] 2014-12-03 19:32
Hello,

Sorry for the delay, I was a bit on other issues with xtreemfs. So.

I just tried with the "full" option:

``` Puppet
  ::xtreemfs::volume {'vmail':
    ensure      => present,
    dir_service => "pbrpcs://${dir}",
    options     => {
      '--admin_password' => hiera('xtreemfs::admin_password'),
      '--pkcs12-file-path'  => '/etc/ssl/certs/xtreemfs-client.p12',
      '--pkcs12-passphrase' => hiera('xtreemfs::service_cred::pwd'),
      '-s'                  => 64,
      '-w'                  => 3,
    },
  }
```

This raises the following error:

``` Puppet
==> mailserver-1: Error: Execution of '/usr/bin/mkfs.xtreemfs --admin_password PASSWORD --pkcs12-file-path /etc/ssl/certs/xtreemfs-client.p12 --pkcs12-passphrase PASSWORD -s 64 -w 3 pbrpcs://192.168.50.2/vmail' returned 1: Invalid parameters found, error: unrecognised option '--admin_password PASSWORD'
==> mailserver-1: 
==> mailserver-1: mkfs.xtreemfs: Create an XtreemFS Volume on a specific MRC.
==> mailserver-1: 
==> mailserver-1: Usage:
==> mailserver-1:   mkfs.xtreemfs [options] [pbrpc[g|s]://]<mrc-host>[:port]/<new-volume-name>
==> mailserver-1: 
==> mailserver-1:   Example: mkfs.xtreemfs localhost/myVolume
==> mailserver-1: 
==> mailserver-1: For complete list of options, please specify -h or --help.
==> mailserver-1: 
==> mailserver-1: Error: /Stage[main]/Fogmail::Role::Client/Xtreemfs::Volume[vmail]/Xtreemfs_volume[vmail]/ensure: change from absent to present failed: Execution of '/usr/bin/mkfs.xtreemfs --admin_password PASSWORD --pkcs12-file-path /etc/ssl/certs/xtreemfs-client.p12 --pkcs12-passphrase PASSWORD -s 64 -w 3 pbrpcs://192.168.50.2/vmail' returned 1: Invalid parameters found, error: unrecognised option '--admin_password PASSWORD'
==> mailserver-1: 
==> mailserver-1: mkfs.xtreemfs: Create an XtreemFS Volume on a specific MRC.
==> mailserver-1: 
==> mailserver-1: Usage:
==> mailserver-1:   mkfs.xtreemfs [options] [pbrpc[g|s]://]<mrc-host>[:port]/<new-volume-name>
==> mailserver-1: 
==> mailserver-1:   Example: mkfs.xtreemfs localhost/myVolume
==> mailserver-1: 
==> mailserver-1: For complete list of options, please specify -h or --help.
```

I tried to switch options in order to see what happens — seems you put some "sort" in the type (which is good). Hence, nothing changed, the error is still the same.

In order to ensure the generated command is correct, I pasted it "as is" in the instance shell, and it works:

``` Bash
root@mailserver-1:~# /usr/bin/mkfs.xtreemfs --admin_password PASSWORD --pkcs12-file-path /etc/ssl/certs/xtreemfs-client.p12 --pkcs12-passphrase PASSWORD -s 64 -w 3 pbrpcs://192.168.50.2/vmail                              
Trying to create the volume: pbrpcs://192.168.50.2/vmail

Using options:
  Mode:                         777
  Access Control Policy:        POSIX

  Default striping policy:              RAID0
  Default stripe size (object size):    64
  Default stripe width (# OSDs):        3

Successfully created volume "vmail" at MRC: pbrpcs://192.168.50.2/vmail
```

Does it help a bit?

Cheers,

C.

**Comment by cjeanneret** [comment] 2014-12-03 19:36
One more thing: it doesn't seem to be able to detect the volume once I create it "by hand": it wants to re-create it :(.

Probably a problem with the lsfs.xtreemfs call?

**Comment by cardil** [comment] 2014-12-03 21:00
Ok. That help me to identify the cause, I think. I'll check it and if it is it, I will make appropriate changes.

Thanks for the info. Stay tuned.

**Comment by cjeanneret** [comment] 2014-12-03 21:09
No problem, I'll test it as soon as there's some correction :). Now that I've solved the SSL part, I'm full on your module for tests.

Lemme know if you need more debugs/tests.

**Comment by cardil** [comment] 2014-12-03 22:24
I've just changed processing options for `**fs.xtreemfs` commands. This, I think, should fix this issue. I've changed:
- changed processing of options
- fix for passing `undef` value for options without parameters
- changed unit tests to accomodate changes
- added more acceptance tests with more complex options

If you can, please test actual `develop` version

**Comment by cjeanneret** [comment] 2014-12-04 18:18
Hello,

Good news, the creation seems to work. I'm running a second full-test on my side, thanks for the really fast correction.

I think I'll get some problems with the mount part, as I have to pass options to the "mount.xtreemfs" command, like:

``` Puppet
mount.xtreemfs \
  --pkcs12-file-path /etc/ssl/certs/xtreemfs-client.p12 \
  --pkcs12-passphrase '<%=@pkcs_password%>' \
  pbrpcs://<%=@dir_service%>/vmail \
  /srv/encfs
```

Also, I think there's a documentation on xtreemfs.org regarding the auto-mount part, as the options aren't in standard "mount format", but I can't find it again. I think they point some /etc/rc.local with a script call in order to perform the automount, or something like that. I cannot be "as is" in the fstab :(.

In a more general thought: it might be good to add a "protocol" option to mkfs, mount and others.

This would allow to get the very same variable for the "dir_service" for all the configurations AND mount/mkfs/rmfs/others. And would prevent confusions for new users, as they might want to use SSL, and will forget/not understand they must put `pbrpcs://$dir_service` in the volume/mount calls…

Cheers,

C.

**Comment by cjeanneret** [comment] 2014-12-04 18:22
ah, test finished: confirmed, the volume is now present \o/.

And, as expected, the mount part fails :(. I might open an issue at xtreemfs level in order to ask for a more "mount-standard" option syntax.

**Comment by cjeanneret** [comment] 2014-12-04 18:35
aannd I found back the "autofs" way:
https://github.com/xtreemfs/xtreemfs/wiki/Mounting-an-XtreemFS-Volume-using-Autofs

I really don't like that way…

Now I stop the spam, sorry.

**Comment by cardil** [comment] 2014-12-04 20:07
So. As the bug has been confirmed, by you, to stop occurring, I will close this issue.

If you feel that some things can be done the other way, mayby better - please open here some new issues. I encurage you to do that. You have mention: 
- mounting with autofs, 
- convention for passing options, 
- possibility to add metaparameter `protocol` to all types.

I feel that they are all worth creating separate issues, so the progress and priorities can be better determined.

Ok? :-)

**Closed as completed by cardil** 2014-12-04 20:07 UTC
Labels: bug
